# Generated by Django 3.0.4 on 2020-03-27 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True, blank=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
