# Generated by Django 3.0.4 on 2020-03-27 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200327_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='credit_Card',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='expired_Card',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secCode_Card',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
